Add flag to updatedb command for site-update script
State-of-Rhode-Island-eCMS/ecms_distribution pull request #83
Opened 2021-02-23 13:18 UTC by ben-hamelin

## Summary

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes/no
| Did you apply meaningful labels to the pull request? | yes/no
| Did you perform a self review first? | yes/no
| Documentation reflects changes? | yes/no
| `CHANGELOG` reflects changes? | yes/no
| Unit/Functional tests reflect changes? | yes/no
| Did you perform browser testing? | yes/no
| Risk level | Low, Medium, High
| Relevant links | JIRA issue, bug reports, security alerts, etc.

2021-02-24 16:24 UTC, ben-hamelin commented
@jordan-caldwell This also adds a fix for the site install issue tracked here:
https://support.acquia.com/hc/en-us/articles/360047676154-Site-Factory-installations-fail-when-memcache-is-included
https://insight.acquia.com/support/tickets/1134572

2021-02-24 16:28 UTC, jordan-caldwell requested changes
Interesting re: the flag. This looks good just one nitpick

2021-02-24 16:28 UTC, jordan-caldwell commented on factory-hooks/post-settings-php/acsfd8+.memcache.settings.php
> +  in_array('site-install',$_SERVER['argv']))
Needs a space after comma

2021-02-24 17:12 UTC, ben-hamelin commented on factory-hooks/post-settings-php/acsfd8+.memcache.settings.php
> +  in_array('site-install',$_SERVER['argv']))
got it!

2021-02-26 14:59 UTC, jordan-caldwell approved these changes
Looks good!

2021-02-26 17:40 UTC, merged